name: push main
on:
  push:
    branches:
      - main
jobs:
  regression-test:
    runs-on: ubuntu-latest
    steps:
      - run: curl -X POST https://i31alzlaca.execute-api.us-east-1.amazonaws.com/dev/r1 -H 'Content-Type:application/json' -d '{"login":"my_login","password":"a_password"}'